# Generated by Django 3.0.7 on 2021-05-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_verify_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_passenger',
            field=models.BooleanField(default=True),
        ),
    ]
